// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhIjOrf_qGbhCI_uQAGmn7WoVAEgoT64',
    appId: '1:737631607251:android:0230f13d806ca8ca99b726',
    messagingSenderId: '737631607251',
    projectId: 'advmobprog-firebase-b87ab',
    storageBucket: 'advmobprog-firebase-b87ab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRXnhZQ7zB_9-Xf34Dt2y5fOERvStqMz4',
    appId: '1:737631607251:ios:7cfff8702837228b99b726',
    messagingSenderId: '737631607251',
    projectId: 'advmobprog-firebase-b87ab',
    storageBucket: 'advmobprog-firebase-b87ab.firebasestorage.app',
    iosBundleId: 'com.example.nacpilMobile',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsV6KF3ZmCpl0EKbuaiSySuDXHkZpFUpo',
    appId: '1:737631607251:web:ff9ca240fd0eb9dc99b726',
    messagingSenderId: '737631607251',
    projectId: 'advmobprog-firebase-b87ab',
    authDomain: 'advmobprog-firebase-b87ab.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-b87ab.firebasestorage.app',
    measurementId: 'G-Z6XW5955BJ',
  );
}
